### ISSUE TITLE
How to convert a Type that implements ToSql into types array

### ISSUE THREAD

**Issue by hazel-ocean** [sfackler/rust-postgres-binary-copy#3]
In the example on the README, you define an array of types: `let types = &[Type::Int4, Type::Varchar];`.

This gets really tedious and error-prone for a struct that has >10 fields or so - is there some function I can just call to convert my struct into this array?

**Comment by sfackler** [comment]
No - Rust types can correspond to multiple Postgres types. For example, a Rust `String` can be converted to and from `TEXT`, `VARCHAR`, `CHAR(n)`, `CITEXT`, etc.

**Comment by hazel-ocean** [comment]
Ah, that makes a lot of sense. And probably any kind of abstraction in front of Rust types, (e.g. some new-types like a `type VarChar = String;` which I could use in my struct definition) would be outside the scope of this crate.
