### ISSUE TITLE
Support for hstore (and maybe other "other" types)

### ISSUE THREAD

**Issue by jbg** [sfackler/rust-postgres-binary-copy#4]
I'm trying to use this to insert rows with an `hstore` column, but it appears to be an `Other` type in the rust-postgres types, and I can't see any public way to instantiate `Other` in order to populate the `types` array.

**Comment by sfackler** [comment]
The simplest way would probably be to prepare a statement using an HSTORE and grab the type out of that:

```rust
let stmt = conn.prepare("SELECT $1::HSTORE").unwrap();
let hstore_type = stmt.param_types[0].clone();
```

**Comment by jbg** [comment]
That's an excellent idea, thanks!
