### ISSUE TITLE
Binary copy with enums

### ISSUE THREAD

**Issue by jamessewell** [sfackler/rust-postgres-binary-copy#6]
Using the `ANYENUM` type with an Enum (which has ToSql and FromSql derived) does not seem to work with PostgreSQL 11 (haven't tested others).

I get this:

`Error(Io(Custom { kind: InvalidInput, error: WrongType(Type(Anyenum))` 

And in the Postgres log:

`ERROR:  COPY from stdin failed:`

I can INSERT data with the Enum correctly so my types seem to be correct on both sides.

**Comment by sfackler** [comment]
`ANYENUM` is a pseudo-type that's only used as part of the type signature for a Postgres function: https://www.postgresql.org/docs/11/datatype-pseudo.html.

You need to use the actual enum type for the enum.

**Comment by jamessewell** [comment]
Hmm. I can't seem to construct a 'Type' as inner is a private field.

Is there any documentation on how to construct a type with Other anywhere?

**Comment by sfackler** [comment]
You can't construct a type yourself, you need to get it from the database (by for example preparing a query relating to it).

**Comment by jamessewell** [comment]
I found a way to construct it using something marked as non-public API (which I should probably not do!).

But point taken, I'll try running a dummy query on the table and doing it that way.
